version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8989:80'
    links:
      - php
  php:
    image: php:7.1-fpm
    volumes:
      - ./app:/app

