version: '3'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - 80:80
    restart: always
networks:
  default:
    external:
      name: nginx-proxy